// <auto-generated />
using System;
using Cashly.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Cashly.Infrastructure.Migrations
{
    [DbContext(typeof(CashlyDbContext))]
    [Migration("20260608111222_CreateClosedMonthsTable")]
    partial class CreateClosedMonthsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Cashly.Domain.CashflowContext.Entities.Cashflow", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK_cashflows");

                    b.ToTable("cashflows", (string)null);
                });

            modelBuilder.Entity("Cashly.Domain.CashflowContext.Entities.ClosedMonth", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("balance");

                    b.Property<Guid>("CashflowId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cashflow_id");

                    b.Property<DateTimeOffset>("ClosedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("closed_at");

                    b.Property<int>("Period")
                        .HasColumnType("int")
                        .HasColumnName("period");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("PK_closed_months");

                    b.HasIndex("CashflowId", "Period")
                        .IsUnique();

                    b.ToTable("closed_months", (string)null);
                });

            modelBuilder.Entity("Cashly.Domain.CollaborationContext.Entities.CashflowMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CashflowId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cashflow_id");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("PK_cashflow_member");

                    b.HasIndex("CashflowId", "Role");

                    b.HasIndex("CashflowId", "UserId")
                        .IsUnique();

                    b.ToTable("cashflow_member", (string)null);
                });

            modelBuilder.Entity("Cashly.Domain.IdentityContext.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("password_hash");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("PK_users");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Cashly.Domain.TransactionContext.Entity.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CashflowId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("cashflow_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("transaction_status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar")
                        .HasColumnName("transaction_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CashflowId");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("Cashly.Domain.CashflowContext.Entities.ClosedMonth", b =>
                {
                    b.HasOne("Cashly.Domain.CashflowContext.Entities.Cashflow", null)
                        .WithMany("ClosedMonths")
                        .HasForeignKey("CashflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cashly.Domain.CollaborationContext.Entities.CashflowMember", b =>
                {
                    b.HasOne("Cashly.Domain.CashflowContext.Entities.Cashflow", null)
                        .WithMany("CashflowMembers")
                        .HasForeignKey("CashflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Cashly.Domain.IdentityContext.Entities.User", b =>
                {
                    b.OwnsOne("Cashly.Domain.IdentityContext.ValueObjects.Name", "Name", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(80)
                                .HasColumnType("nvarchar(80)")
                                .HasColumnName("last_name");

                            b1.HasKey("UserId");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("Cashly.Domain.TransactionContext.Entity.Transaction", b =>
                {
                    b.HasOne("Cashly.Domain.CashflowContext.Entities.Cashflow", null)
                        .WithMany()
                        .HasForeignKey("CashflowId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Cashly.Domain.CashflowContext.Entities.Cashflow", b =>
                {
                    b.Navigation("CashflowMembers");

                    b.Navigation("ClosedMonths");
                });
#pragma warning restore 612, 618
        }
    }
}
