services:
  cashly-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: cashly-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: ${MSSQL_SA_PASSWORD}
    ports:
      - "1433:1433"
    volumes:
      - cashly_sqlserver_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  cashly_sqlserver_data: